### ISSUE TITLE
Intent to relicense under MIT license

### ISSUE THREAD

**Issue by djzort** [djzort/NetAddr-MAC#4]
See also https://en.wikipedia.org/wiki/MIT_License and https://metacpan.org/pod/Software::License::MIT

Contributors need to sign off:

@ollyg yes and ownership go to myself ongoing

@irgeek

**Comment by djzort** [comment]
From @ollyg 
db1b1e34d5f37dffeb9d72cf436507ec89e76f45
6826ffa0f0a092aba837e4126c2f54d75b31b18b


From @irgeek
d0b80a9d8d840020b6d4478ca1590e84a58006a8
7805726c085f2aca782edc0bdab4412cd3588927

**Comment by djzort** [comment]
> It's not clear to me what you need us to do with this issue.

Hi @irgeek you made two contributions as listed above. I therefore need your agreement to relicense them. You might also like to agree to gift copyright ownership of them to me ongoing.

**Comment by djzort** [comment]
@irgeek i tried to email the (at)linode address you used when contributing but unfortunately it bounced.

I would like to move things along, i just need a "yes" from you

As current maintainer I intend to relicense from A1.0/GPL1.0+ to MIT

You made a contribution to NetAddr::MAC in the past and as a contributor you still hold copyright controls over your contributions so your approval is needed. 

You might also be kind enough to relinquish copyright controls to myself.

**Comment by irgeek** [comment]
yes

**Comment by ollyg** [comment]
also yes for me for both relicense and gift copyright. many thanks!

**Comment by djzort** [comment]
Excellent. Thanks all.
